apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: lab-exercise
  annotations: #Application Load Balancer will be created based on the annotations in AWS
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    #this annotations is useful to keep only one ALB under guru1188 group. if you don't give this it will create another ALB.
    alb.ingress.kubernetes.io/group.name: guru1188
spec:
  ingressClassName: alb #Load Balancer type as Application Load Balancer
  rules:
  - host: "frontend.guru97s.cloud" #ALB rule
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: frontend #ALB Target Group, your service name
            port:
              number: "{{ .Values.ingress.portNumber }}"
# here Annotations are used in Ingress in order to create external resource in AWS i,.e ALB(Application Load Balancer)
# $ kubectl get pods -n kube-system
# $ kubectl logs <aws-load-balancer-controller-66578vd711-l7epd> -n kube-system
# $ kubectl get svc
# $ kubectl get ingress
# $ kubectl describe <ingress-name>
# Before accessing frontend application in the browser make sure that the Route 53 record created for Application Load Balancer with record name: *.guru97s.cloud,type: CNAME,select Alias to Application and Class Load Balancer,us-east-1,in load balancer select Application Load Balancer which is recently created by Kubernetes Cluster 