apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lab-exercise
spec:
  selector:
    app: frontend
    project: lab-exercise
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080 #container-port